### ISSUE TITLE
Copy to clipboard button

### ISSUE THREAD

**Issue by ahmedelbilal** [ahmedelbilal/404-pages#2]
Copy to clipboard button in the top right corner of the code preview page

![Screenshot from 2022-10-29 16-09-44](https://user-images.githubusercontent.com/47687479/198836119-a0cc3722-7a35-4693-9c7e-bd84ed3da68a.png)

**Comment by Alien10123** [comment]
Can I do this? And if so is there a specific icon library I should use or should I just use any good looking one?

**Comment by ahmedelbilal** [comment]
Can you put it here @Alien10123  ?
![Group 1](https://user-images.githubusercontent.com/47687479/198867367-b2fa8f92-3c46-4074-a3a7-d03399effec2.jpg)

**Comment by Alien10123** [comment]
k. I will do it now.

**Comment by ahmedelbilal** [comment]
Ok go ahead

**Comment by Alien10123** [comment]
Done

**Comment by ahmedelbilal** [comment]
Thanks a lot @Alien10123
