### ISSUE TITLE
Add prettier

### ISSUE THREAD

**Issue by ahmedelbilal** [ahmedelbilal/404-pages#4]
Add prettier with this configuration

```
{
  "trailingComma": "es5",
  "tabWidth": 2,
  "semi": false,
  "singleQuote": true
}
```

**Comment by logicalahara** [comment]
Hey @ahmed-sudani, would love to contribute to this. Will you please add 'hacktoberfest' label to this issue and assign it to me ?

**Comment by ahmedelbilal** [comment]
You are welcome, please go ahead @logicalahara

**Comment by logicalahara** [comment]
I think this repo is not a part of hacktoberfest, will you please participate and add hacktoberfest label to repo itself ?

**Comment by ahmedelbilal** [comment]
Okay go ahead @logicalahara

**Comment by logicalahara** [comment]
@ahmed-sudani Please review https://github.com/ahmed-sudani/404-pages/pull/9.

I request you to please add 'hacktoberfest-accepted' post successful review today if possible

**Comment by logicalahara** [comment]
@ahmed-sudani any progress over the above ?
